/**
* Nsmf_PDUSession
* SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* SMContextsCollectionApiImpl.h
*
* 
*/

#ifndef SM_CONTEXTS_COLLECTION_API_IMPL_H_
#define SM_CONTEXTS_COLLECTION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <SMContextsCollectionApi.h>

#include <pistache/optional.h>

#include "Inline_object.h"
#include "ProblemDetails.h"
#include "SmContextCreateError.h"
#include "SmContextCreatedData.h"

namespace oai {
namespace smf {
namespace api {

using namespace oai::smf::model;

class SMContextsCollectionApiImpl : public oai::smf::api::SMContextsCollectionApi {
public:
    SMContextsCollectionApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~SMContextsCollectionApiImpl() {}

    void post_sm_contexts(const Inline_object &inlineObject, Pistache::Http::ResponseWriter &response);

};

}
}
}



#endif